#!/bin/bash

# Render Deployment Commands
# Execute these commands to deploy to Render

echo "=== Manual Deployment Steps for Render ==="
echo ""
echo "1. Create Render account (if not already done):"
echo "   https://dashboard.render.com/register"
echo ""
echo "2. Install Render CLI (if not installed):"
echo "   brew tap render-oss/render && brew install render"
echo ""
echo "3. Login to Render:"
echo "   render login"
echo ""
echo "4. Create new Blueprint deployment:"
echo "   render blueprint launch"
echo "   - Select your render.yaml file"
echo "   - Choose your GitHub repository"
echo "   - Configure environment variables"
echo ""
echo "5. Or deploy via GitHub:"
echo "   a. Push render.yaml to your repository"
echo "   b. Go to https://dashboard.render.com"
echo "   c. Click 'New' > 'Blueprint'"
echo "   d. Connect your GitHub repository"
echo "   e. Render will auto-detect render.yaml"
echo ""
echo "6. Set required environment variables in dashboard:"
echo "   - AUTH0_CLIENT_SECRET"
echo "   - Any other sensitive variables"
echo ""
echo "7. Monitor deployment:"
echo "   - Check build logs"
echo "   - Verify health checks"
echo "   - Test endpoints"
echo ""
echo "8. Custom domain setup (optional):"
echo "   - Add custom domain in Render dashboard"
echo "   - Update DNS records"
echo "   - Update CORS_ALLOWED_ORIGINS"
echo ""
