[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
# Multi-service deployment: supervisord manages Caddy + FastAPI
startCommand = "supervisord -c /etc/supervisor/conf.d/supervisord.conf"

[env]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "info"
FASTAPI_PORT = "8000"
CADDY_PROXY_MODE = "true"
CORS_ORIGINS = "[\"https://app.zebra.associates\",\"http://localhost:3000\",\"http://localhost:3001\"]"

# CRITICAL FIX: Multi-service deployment with Caddy proxy
# Caddy proxy handles CORS on port 80 (external)
# FastAPI backend runs on port 8000 (internal)
# Supervisord manages both services