[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
# CORS-001: Use supervisord instead of start.sh directly

[env]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "info"
PORT = "8000"
CADDY_PROXY_MODE = "false"

# CRITICAL FIX: Single-service deployment for Railway compatibility
# FastAPI handles CORS directly on port 8000
# Railway edge proxy provides HTTPS termination