[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
# CORS-001: Use supervisord instead of start.sh directly

[env]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "info"
PORT = "80"
CADDY_PROXY_MODE = "true"
FASTAPI_INTERNAL_PORT = "8000"

# CORS-001: Multi-service configuration
# Caddy reverse proxy handles external traffic on port 80
# FastAPI backend runs internally on port 8000