[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "./start.sh"

[env]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
PORT = "8000"

# No volumes - this is a FastAPI backend service
# Database connections via Railway internal network