services:
  - type: web
    name: marketedge-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./render-startup.sh"
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: RUN_MIGRATIONS
        value: true
      - key: PORT
        fromService:
          type: web
          name: marketedge-backend
          property: port
