# Render.yaml Configuration for MarketEdge Platform
# Production and Preview Environment Setup

# Preview Environment Configuration
previews:
  generation: automatic  # Generate preview environments for all PRs automatically
  expireAfterDays: 7     # Clean up preview environments after 7 days

services:
  # Main Backend Service (FastAPI)
  - type: web
    name: marketedge-platform
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./render-startup.sh"
    plan: free

    # Environment Groups - Link to existing production-env group with 23 variables
    envGroup: production-env

    # Preview environment overrides
    previews:
      plan: free  # Use free tier for preview environments
      numInstances: 1

    envVars:
      # Environment identification
      - key: ENVIRONMENT
        value: production
        previewValue: staging

      # Migration control
      - key: RUN_MIGRATIONS
        value: true

      # Port configuration
      - key: PORT
        fromService:
          type: web
          name: marketedge-platform
          property: port

      # Database configuration - inherited from environment group
      - key: DATABASE_URL
        sync: false  # Set manually in environment group

      # Auth0 Configuration (Production)
      - key: AUTH0_DOMAIN
        sync: false  # Set manually in Render dashboard
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false

      # Auth0 Configuration (Staging/Preview Environments)
      - key: AUTH0_DOMAIN_STAGING
        sync: false  # Set manually in Render dashboard
      - key: AUTH0_CLIENT_ID_STAGING
        sync: false  # Set manually in Render dashboard
      - key: AUTH0_CLIENT_SECRET_STAGING
        sync: false  # Set manually in Render dashboard
      - key: AUTH0_AUDIENCE_STAGING
        sync: false  # Set manually in Render dashboard

      # Environment-aware Auth0 selection
      - key: USE_STAGING_AUTH0
        value: "false"
        previewValue: "true"

      # Redis Configuration - inherited from environment group
      - key: REDIS_URL
        sync: false  # Set manually in environment group

      # CORS Configuration
      - key: CORS_ORIGINS
        value: "https://platform.marketedge.co.uk,https://marketedge-platform.onrender.com"
        previewValue: "https://*.onrender.com,https://localhost:3000"  # Wildcard support for preview environments

      # Feature Flags
      - key: ENABLE_DEBUG_LOGGING
        value: "false"
        previewValue: "true"

      # Security
      - key: SECRET_KEY
        generateValue: true

      # Monitoring
      - key: SENTRY_DSN
        sync: false
        previewValue: ""  # Disable Sentry for preview environments