type: web
name: marketedge-platform
runtime: python3
plan: free
buildCommand: |
  pip install -r requirements.txt
  echo "Applying migration 003 for analytics_modules table..."
  python -m alembic upgrade 003
  echo "Migration 003 applied successfully"
startCommand: |
  echo "Starting MarketEdge Platform..."
  echo "Verifying analytics_modules table exists..."
  python -c "
  import asyncio
  import asyncpg
  import os
  async def check():
      conn = await asyncpg.connect(os.environ['DATABASE_URL'])
      exists = await conn.fetchval('SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = \'analytics_modules\')')
      print(f'Analytics modules table exists: {exists}')
      await conn.close()
  asyncio.run(check())
  "
  gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
healthCheckPath: /health
autoDeploy: true
envVars:
  - key: ENVIRONMENT
    value: production
  - key: DEBUG
    value: false
