# Render Blueprint for MarketEdge Platform
# Epic 2: Railway to Render Migration
# Generated: 2025-08-16
# Version: 2.0.0

services:
  # Main web service - Multi-service container (Caddy + FastAPI)
  - type: web
    name: marketedge-platform
    runtime: docker
    # repo: https://github.com/zebraassociates-projects/platform-wrapper
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    
    # Resource allocation
    plan: standard  # Provides adequate resources for production
    
    # Health check configuration
    healthCheckPath: /health/
    numInstances: 1  # Start with 1, scale as needed
    
    # Persistent storage for logs
    disk:
      name: marketedge-logs
      mountPath: /var/log
      sizeGB: 10  # Increased for production logging
    
    # Environment variables
    envVars:
      # ===== Core Application Settings =====
      - key: PORT
        value: 80  # Caddy proxy port
      - key: FASTAPI_PORT
        value: 8000  # FastAPI backend port
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: PROJECT_NAME
        value: Platform Wrapper
      - key: PROJECT_VERSION
        value: 2.0.0
      - key: API_V1_STR
        value: /api/v1
      
      # ===== Caddy Proxy Configuration =====
      - key: CADDY_PROXY_MODE
        value: true
      - key: CADDY_AUTO_HTTPS
        value: off  # Render handles SSL
      
      # ===== Database Configuration =====
      - key: DATABASE_URL
        fromDatabase:
          name: marketedge-postgres
          property: connectionString
      
      # ===== Redis Configuration =====
      - key: REDIS_URL
        fromDatabase:
          name: marketedge-redis
          property: connectionString
      
      # ===== Auth0 Configuration =====
      - key: AUTH0_DOMAIN
        value: dev-g8trhgbfdq2sk2m8.us.auth0.com
      - key: AUTH0_CLIENT_ID
        sync: false  # Set manually in Render dashboard
      - key: AUTH0_CLIENT_SECRET
        sync: false  # Set manually in Render dashboard
      - key: AUTH0_CALLBACK_URL
        value: https://marketedge-platform.onrender.com/callback
      
      # ===== Security & JWT =====
      - key: JWT_SECRET_KEY
        generateValue: true  # Render generates secure random value
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      
      # ===== CORS Configuration =====
      - key: CORS_ORIGINS
        value: '["https://app.zebra.associates","https://marketedge-frontend.onrender.com","http://localhost:3000","http://localhost:3001"]'
      - key: CORS_ALLOWED_ORIGINS
        value: https://app.zebra.associates,https://marketedge-frontend.onrender.com,http://localhost:3000,http://localhost:3001
      
      # ===== Rate Limiting =====
      - key: RATE_LIMIT_ENABLED
        value: true
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: 60
      - key: RATE_LIMIT_BURST_SIZE
        value: 10
      
      # ===== Data Layer Configuration =====
      - key: DATA_LAYER_ENABLED
        value: false
      # Uncomment if enabling Supabase integration
      # - key: DATA_LAYER_SUPABASE__URL
      #   sync: false
      # - key: DATA_LAYER_SUPABASE__KEY
      #   sync: false
      
      # ===== Monitoring & Performance =====
      - key: ENABLE_METRICS
        value: true
      - key: METRICS_PORT
        value: 9090
      - key: TRACE_ENABLED
        value: false  # Enable for debugging
      
      # ===== Multi-tenant Configuration =====
      - key: MULTI_TENANT_ENABLED
        value: true
      - key: DEFAULT_TENANT_ID
        value: default
      
      # ===== Feature Flags =====
      - key: FEATURE_USER_MANAGEMENT
        value: true
      - key: FEATURE_ADMIN_PANEL
        value: true
      - key: FEATURE_MARKET_EDGE
        value: true
      - key: FEATURE_CAUSAL_EDGE
        value: true
      - key: FEATURE_VALUE_EDGE
        value: true

# Database services
databases:
  # PostgreSQL database
  - name: marketedge-postgres
    databaseName: marketedge_production
    user: marketedge_user
    plan: standard  # Production-ready plan
    ipAllowList: []  # Configure if needed for security
    
  # Redis for caching and rate limiting
  - name: marketedge-redis
    plan: standard  # Production-ready plan
    maxmemoryPolicy: allkeys-lru  # Optimize for cache usage
    ipAllowList: []  # Configure if needed for security

# Environment variable groups for better organization
envVarGroups:
  # Sensitive Auth0 credentials
  - name: auth0-secrets
    envVars:
      - key: AUTH0_CLIENT_ID
        value: mQG01Z4lNhTTN081GHbR9R9C4fBQdPNr
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false  # Must be set manually for security
      
  # Database credentials (if not using auto-connection)
  - name: database-secrets
    envVars:
      - key: DATABASE_PASSWORD
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      
  # API keys and external services
  - name: external-services
    envVars:
      - key: SENTRY_DSN
        sync: false
      - key: DATADOG_API_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false

# Build configuration
buildFilter:
  paths:
    - backend/**
  ignoredPaths:
    - backend/tests/**
    - backend/docs/**
    - backend/.pytest_cache/**
    - backend/__pycache__/**