name: Validate Render Configuration

on:
  pull_request:
    paths:
      - 'render.yaml'
      - 'scripts/validate-render-yaml.sh'
      - '.github/workflows/validate-render-config.yml'
  push:
    branches:
      - main
      - staging
    paths:
      - 'render.yaml'

jobs:
  validate:
    name: Validate render.yaml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyYAML
        run: |
          pip install pyyaml

      - name: Make validation script executable
        run: chmod +x ./scripts/validate-render-yaml.sh

      - name: Validate render.yaml
        run: ./scripts/validate-render-yaml.sh

      - name: Post validation results
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `
            ❌ **Render Configuration Validation Failed**

            The \`render.yaml\` file has validation errors. Please review the workflow logs for details.

            Common issues:
            - Environment variables cannot have both \`value\` and \`sync: false\`
            - Secrets should have \`sync: false\` without a \`value\` field
            - Variables with \`fromGroup\`, \`fromDatabase\`, or \`fromService\` cannot have \`sync\`

            Run locally: \`./scripts/validate-render-yaml.sh\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Post validation success
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `
            ✅ **Render Configuration Validation Passed**

            The \`render.yaml\` file is valid and ready for deployment.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });